services:
  backend:
    build: .
    ports:
      - '3000:3000'
      - '5555:5555'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      # - /usr/src/app/dist
    command: ["npm", "run", "start:dev"]

  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
